# This is a basic CI (Continuous Integration) workflow to help you get started with Automation.
# It runs quality checks every time you push code or open a pull request.

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code so the workflow can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Step 3: Run the linting command to check HTML errors
      - name: Lint HTML
        run: npx -y htmlhint "*.html"

      
